spring:
  application:
    name: spring-ai
  ai:
    model.chat: ollama
    ollama.chat.options.model: deepseek-r1:8b
  main:
    banner-mode: off
    spring:
    web-application-type: none

  mcp:
    server:
      enabled: true
      name: my-weather-server
      version: 0.0.1
      type: SYNC

logging:
  pattern:
    console:
